# Generated by Django 5.2.7 on 2025-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assets/thumbnails/')),
                ('asset_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
